### ISSUE TITLE
Lightly object detection input: Key error

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/labelformat#9]
The line [here](https://github.com/lightly-ai/labelformat/blob/0cf58e3bba7e38d54ca96be5f2626b2787043694/src/labelformat/formats/lightly.py#L65) fails with a `KeyError` if there is a Lightly object detection label in the input folder that doesn't have a corresponding image in the images folder. The error message is not descriptive and I had to dig into the code in order to understand what went wrong.

I'm not sure what's the best way to fix this. I see three options:
* Raise a custom error with a descriptive error message.
* Check if the label has a corresponding image. If not just continue.
* Check if the label has a corresponding image. If not raise a warning and continue.

Let me know what you'd prefer. I'm happy to make a pull request and fix it.

**Comment by michal-lightly** [comment]
Thanks for the issue report!

I suggest to be strict with opt-out:
* By default, print a descriptive error.
* Offer `--skip-labels-without-image` (better name is welcome) option to bypass.

**Comment by philippmwirth** [comment]
I just looked at the code and there's an inconsistency between the [Kitti](https://github.com/lightly-ai/labelformat/blob/main/src/labelformat/formats/kitti.py) and [Lightly](https://github.com/lightly-ai/labelformat/blob/main/src/labelformat/formats/lightly.py) format:

For Kitti, `get_labels` iterates over all images in the image directory and returns only labels for existing images:
```python
    def get_labels(self) -> Iterable[ImageObjectDetection]:
        category_name_to_category = {cat.name: cat for cat in self._categories}

        for image in self.get_images():
            label_path = (self._input_folder / image.filename).with_suffix(".txt")
            if not label_path.exists():
                logger.warning(
                    f"Label file '{label_path}' for image '{image.filename}' does not exist."
                )
```

For Lightly, the method iterates over the labels and raises the `KeyError` reported above if the corresponding image doesn't exist.

IMO if we touch the code we should make it consistent so my proposal is to:
* Raise `ImageNotFoundError` instead of `KeyError` in Lightly object detection labels.
* Refactor Kitti labels to work the same way and raise `ImageNotFoundError` there, too.
* Add `--skip-labels-without-image` for both.

**Comment by michal-lightly** [comment]
Sounds good to me ✅
